### PR TITLE
Make backtrace cleaning optional

### LINKED ISSUE #228: Option to skip backtrace cleaning?
I'm wondering if I should create a pull request with the option to skip backtrace cleaning. My use case is that when my application throws an exception from inside a gem I don't get any backtrace.

Or perhaps if the backtrace is cleaned to nothing it should use the untouched backtrace instead?

Let me know if you'd like a pull request for either of these ideas.

### PR DESCRIPTION
**Pull request by chancancode**
Hello!

This is a starting point to fix #228. It adds a new config `clean_backtrace` (defaults to `true`) for changing whether backtraces should be cleaned.

Also fixed a bug where the backtrace of background exceptions are not ran through the backtrace cleaner currently – I'm unsure if this was intentional, but it was easier to "fix" this so that the test would pass. If that's unacceptable, feel free to pick it up from here and improve the code.

To maintain the current behavior, the new option is defaulted to `true`. However, personally, I feel that this whole feature (backtrace cleaning) is of dubious values in these exception emails. I came across this when helping a client debug an error they are encountering, but unfortunately the error is originated from a gem so I didn't have any backtrace to look at. It seems like you would always want to have more information in these reports... I'm not sure if there's much value in having the option to clean the backtrace in the first place in this context.

The backtrace cleaning code is also only used in the `EmailNotifier`, so if this is staying, it should probably be moved up one layer so that it would be consistent across the `WebhookNotifier` (for example) and the chat notifiers as well (in theory, the cleaner could remove some of the top frames in the backtrace as well).

Like I said, this is only a starting point, so if it doesn't fit your needs for some reason, feel free to pick it up and improve it or reimplement in another way. Would love to see this feature go into the master branch eventually!

Thanks for reviewing this, hope it helps! :heart: :yellow_heart: :green_heart: :blue_heart: :purple_heart:

Fixes #228

### CODE REVIEW

**Comment by vala** [comment]
Any chance that this can be merged at some point ?

**Comment by smartinez87** [comment]
@vala are you still experiencing problems with the backtrace?

**Comment by elfenars** [comment]
+1

Having this would be very nice, right now (specially with Sidekiq) I get very little info and would really like to have the full backtrace sometimes.

**Comment by luis-luna-aguilar** [comment]
+1 the full stack trace would save you some time of log digging when you need more info.

**Comment by vala** [comment]
@smartinez87 Sorry for the delay, but the backtrace is still cleaned up in the latest versions of Exception Notification for me

**Comment by smartinez87** [comment]
closing this PR in favor of #328

**Pull request closed without merging**
