### PR TITLE
Removed \n into irc notifier message

### PR DESCRIPTION
**Pull request by jgengo**
Hello,

I've to remove \n into the message when it's supposed to be sent into IRC.
Maybe would have been better to split by this character and send a message for each line, but it suits well for my usage.

Feel free to accept this Pull Request if you like it 👍 

Thank you!

### CODE REVIEW

**Comment by EmilioCristalli** [comment]
hi @jgengo , thanks for the PR!

I'm not sure if i understand what you are trying to fix. Is it because `exception.message ` can have `\n`s?

If so, does it happen frequently? do you have an example?

I wonder if it would be better to do this in a `pre_callback` hook to avoid handling one-off cases in the gem.

Just realizing this feature is nor really documented but I think you can do something like this:

```ruby 
config.middleware.use ExceptionNotification::Rack,
  irc: {
    domain: 'irc.example.com'
    pre_callback: ->(opts, notifier, backtrace, message, message_opts) { message.tr!("\n", ' ') }
  }
```

Let us know what you think

**Comment by jgengo** [comment]
Hello!

Yes, I think your solution could work and would be enough. I had to edit it for a previous project already live so it's fine for me now. (it's a 1 year PR).

And yes if you have \n it will just send your first part but not the other one. and for my usage, I needed to handle it. Your notification error bugs contain \n and while trying to write it on IRC it only shows the first part which was not really relevant.

Br,
Jordane

**Comment by EmilioCristalli** [comment]
@jgengo yeah, sorry it took so long to review :( 

what do you think about closing this PR then?

**Comment by jgengo** [comment]
yes that's fine I close it :)

**Pull request closed without merging**
