### PR TITLE
Bugfix - Add exception_data to Mattermost notifier message

### LINKED ISSUE #490: exception_data not set in mattermost notifier
### Steps to reproduce
1. Setup mattermost notifier. 
2. Add current user data as descriped in https://github.com/smartinez87/exception_notification#custom-data-eg-current-user

### Expected behavior
additional data would appear in mattermost message

### Actual behavior
No data added. Check https://github.com/smartinez87/exception_notification/blob/d5474e0a8d80adaa83328ea803ad860dd5698d94/lib/exception_notifier/mattermost_notifier.rb#L39

### PR DESCRIPTION
**Pull request by camillof**
Fixes #490 

image

### CODE REVIEW

**Comment by smartinez87** [comment]
@camillof looks great, thanks for contributing!
Do you mind checking on the Rubocop offense so we can get Travis green and merge it?
Thanks!

**Comment by camillof** [comment]
> @camillof looks great, thanks for contributing!
> Do you mind checking on the Rubocop offense so we can get Travis green and merge it?
> Thanks!

Thanks for the heads up @smartinez87 ! It's fixed now 🙌

**Comment by Fleick** [comment]
@smartinez87 
Would it be possible to make a new version release to make these changes directly available via rubygems?
We are currently using this gem with the Mattermost notifier and are currently facing the problem of adding additional information to the notifier, such as on which system the error occurred. Switching from rubygems directly to the master branch is not a real alternative according to our internal guidelines.

Translated with www.DeepL.com/Translator (free version)

**Comment by smartinez87** [comment]
hey @Fleick, thanks for the reminder! I've just released a new version containing this and other fixes https://rubygems.org/gems/exception_notification/versions/4.4.1

**Pull request merged**
