### PR TITLE
added :include_controller_and_action_names_in_subject as option for EmailNotifier

### PR DESCRIPTION
**Pull request by ImMatureTony**
Addresses this "issue":
https://github.com/smartinez87/exception_notification/issues/373

### CODE REVIEW

**Comment by smartinez87** [comment]
hi @ImMatureTony, thanks for contributing!

could you please check the failing test? once it's green I'll merge it.

**Comment by ImMatureTony** [comment]
@smartinez87 Checked the failing test, it's one I added to verify the existing default behavior (i.e. controller/action names *included* in the email subject). Seems like a test that should have been in there in the first place.

Thing is, it passes on Rails 5 but fails on Rails 4, even if I revert the changes this PR makes and just add the test. This seems like a problem with the testing harness setting up request.env incorrectly (it lacks the 'action_controller.instance' key)? My company uses this gem, is running Rails 4.2 and *is* seeing the controller/action names in the e-mails, so I gather the 'action_controller.instance' key must exist in Rails 4.2...

Would you like me to remove this test and merge in the meantime or some other course of action?

**Comment by smartinez87** [comment]
@ImMatureTony yeah, that sounds good

**Comment by smartinez87** [comment]
thanks!

**Comment by ImMatureTony** [comment]
🙌

**Pull request merged**
