### PR TITLE
Updating Contribution

### PR DESCRIPTION
**Pull request by Rubysecret**
How to run tests the standard efficient way

### CODE REVIEW

**Comment by Rubysecret** [comment]
@smartinez87 This is Ruby's secret team from RGSoC . From our frequent working with the gem we found that the old way gave us lots of errors but this method made the tests ran smoothly.

**Comment by Rubysecret** [comment]
`
An ActionController::InvalidAuthenticityToken occurred in courses#index:

ActionController::InvalidAuthenticityToken


          

Request

    URL: http://localhost:3000/courses/index
    HTTP Method: POST
    IP Address: 127.0.0.1
    Parameters: {"a1"=>"666556", "a2"=>"53297", "a3"=>"645795", "a4"=>"600516", "a5"=>"926598", "a6"=>"84522", "a7"=>"127829", "a8"=>"551906", "a9"=>"476595", "a10"=>"2590", "a11"=>"87750", "a12"=>"648263", "a13"=>"52669", "a14"=>"811155", "a15"=>"491859", "a16"=>"36946", "a17"=>"342517", "a18"=>"510838", "a19"=>"362211", "a20"=>"937779", "a21"=>"915809", "a22"=>"31207", "a23"=>"859939", "a24"=>"199551", "a25"=>"714671", "a26"=>"145296", "a27"=>"511939", "a28"=>"877461", "a29"=>"90339", "a30"=>"330444", "a31"=>"2352", "a32"=>"474864", "a33"=>"523504", "a34"=>"292231", "a35"=>"226610", "a36"=>"692361", "a37"=>"323501", "a38"=>"900357", "a39"=>"759008", "a40"=>"861731", "a41"=>"40739", "a42"=>"31494", "a43"=>"662823", "a44"=>"305074", "a45"=>"481256", "a46"=>"217460", "a47"=>"48601", "a48"=>"489445", "a49"=>"278514", "a50"=>"554851", "a51"=>"130572", "a52"=>"729922", "a53"=>"349413", "a54"=>"936367", "a55"=>"962707", "a56"=>"94556", "a57"=>"884952", "a58"=>"877723", "a59"=>"442509", "a60"=>"443907", "a61"=>"174594", "a62"=>"934331", "a63"=>"385506", "a64"=>"158972", "a65"=>"333887", "a66"=>"564768", "a67"=>"932572", "a68"=>"975400", "a69"=>"156512", "a70"=>"409531", "a71"=>"102074", "a72"=>"300752", "a73"=>"549938", "a74"=>"639051", "a75"=>"298722", "a76"=>"682479", "a77"=>"892462", "a78"=>"615669", "a79"=>"678401", "a80"=>"377074", "a81"=>"8834", "a82"=>"65200", "a83"=>"184102", "a84"=>"129335", "a85"=>"983457", "a86"=>"749940", "a87"=>"291874", "a88"=>"434163", "a89"=>"151244", "a90"=>"857202", "a91"=>"79538", "a92"=>"523025", "a93"=>"222771", "a94"=>"21000", "a95"=>"887593", "a96"=>"670602", "a97"=>"903367", "a98"=>"575034", "a99"=>"25188", "a100"=>"404157", "a101"=>"613051", "a102"=>"54777", "a103"=>"342432", "a104"=>"463946", "a105"=>"710614", "a106"=>"522568", "a107"=>"844024", "a108"=>"77046", "a109"=>"991338", "a110"=>"288561", "a111"=>"738270", "a112"=>"139141", "a113"=>"592759", "a114"=>"939905", "a115"=>"345028", "a116"=>"737098", "a117"=>"295364", "a118"=>"311790", "a119"=>"596201", "a120"=>"26278", "a121"=>"274229", "a122"=>"514689", "a123"=>"651274", "a124"=>"606677", "a125"=>"907590", "a126"=>"264516", "a127"=>"402719", "a128"=>"641078", "a129"=>"584567", "a130"=>"861367", "a131"=>"172200", "a132"=>"825327", "a133"=>"751136", "a134"=>"789226", "a135"=>"123732", "a136"=>"208831", "a137"=>"480619", "a138"=>"887556", "a139"=>"208548", "a140"=>"65584", "a141"=>"745051", "a142"=>"420193", "a143"=>"221249", "a144"=>"879730", "a145"=>"111483", "a146"=>"434746", "a147"=>"776893", "a148"=>"167351", "a149"=>"535190", "a150"=>"333172", "a151"=>"188739", "a152"=>"495156", "a153"=>"39574", "a154"=>"755516", "a155"=>"158527", "a156"=>"668874", "a157"=>"227304", "a158"=>"461284", "a159"=>"142656", "a160"=>"766986", "a161"=>"169505", "a162"=>"404136", "a163"=>"541567", "a164"=>"432213", "a165"=>"693827", "a166"=>"883322", "a167"=>"997638", "a168"=>"524791", "a169"=>"127161", "a170"=>"937759", "a171"=>"329828", "a172"=>"175596", "a173"=>"768858", "a174"=>"528248", "a175"=>"993295", "a176"=>"931648", "a177"=>"486163", "a178"=>"41933", "a179"=>"224501", "a180"=>"411861", "a181"=>"855763", "a182"=>"856954", "a183"=>"884755", "a184"=>"375442", "a185"=>"665469", "a186"=>"873531", "a187"=>"736052", "a188"=>"477799", "a189"=>"123351", "a190"=>"423750", "a191"=>"896556", "a192"=>"827565", "a193"=>"326007", "a194"=>"284483", "a195"=>"849815", "a196"=>"400426", "a197"=>"516342", "a198"=>"108704", "a199"=>"162890", "a200"=>"718032", "a201"=>"229732", "a202"=>"404278", "a203"=>"996471", "a204"=>"509578", "a205"=>"517039", "a206"=>"507923", "a207"=>"572308", "a208"=>"596919", "a209"=>"30235", "a210"=>"901973", "a211"=>"311455", "a212"=>"14351", "a213"=>"205396", "a214"=>"586211", "a215"=>"595694", "a216"=>"320266", "a217"=>"600145", "a218"=>"136257", "a219"=>"873900", "a220"=>"963436", "a221"=>"876748", "a222"=>"369774", "a223"=>"848715", "a224"=>"204150", "a225"=>"597155", "a226"=>"906840", "a227"=>"374772", "a228"=>"743909", "a229"=>"359803", "a230"=>"967842", "a231"=>"90614", "a232"=>"338068", "a233"=>"32228", "a234"=>"173489", "a235"=>"840186", "a236"=>"233529", "a237"=>"599294", "a238"=>"584538", "a239"=>"836222", "a240"=>"26173", "a241"=>"230196", "a242"=>"265816", "a243"=>"394666", "a244"=>"241909", "a245"=>"61698", "a246"=>"48437", "a247"=>"95211", "a248"=>"199203", "a249"=>"505361", "a250"=>"70116", "a251"=>"138460", "a252"=>"715657", "a253"=>"52713", "a254"=>"71346", "a255"=>"770716", "a256"=>"252565", "a257"=>"25579", "a258"=>"549954", "a259"=>"426025", "a260"=>"234038", "a261"=>"15993", "a262"=>"688751", "a263"=>"78506", "a264"=>"150532", "a265"=>"394911", "a266"=>"133745", "a267"=>"317808", "a268"=>"672866", "a269"=>"385137", "a270"=>"53866", "a271"=>"141449", "a272"=>"843949", "a273"=>"897978", "a274"=>"714125", "a275"=>"529194", "a276"=>"579955", "a277"=>"773623", "a278"=>"629236", "a279"=>"861798", "a280"=>"803568", "a281"=>"983655", "a282"=>"471877", "a283"=>"140449", "a284"=>"907984", "a285"=>"857280", "a286"=>"962836", "a287"=>"362214", "a288"=>"714896", "a289"=>"527145", "a290"=>"587178", "a291"=>"686703", "a292"=>"143213", "a293"=>"856418", "a294"=>"509718", "a295"=>"758469", "a296"=>"496041", "a297"=>"28760", "a298"=>"133236", "a299"=>"285560", "a300"=>"978574", "controller"=>"courses", "action"=>"index"}
    Timestamp: 2016-09-02 15:20:22 UTC
    Server: mayar-VirtualBox
    Rails root: /home/mayar/my_change
    Process: 20846

Session

    session_id: nil
    data: {}

Environment
#<ActionDispatch::Request:0xa055604>

    CONTENT_LENGTH: 3448
    CONTENT_TYPE: application/x-www-form-urlencoded
    GATEWAY_INTERFACE: CGI/1.2
    HTTP_ACCEPT: */*
    HTTP_ACCEPT_ENCODING: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
    HTTP_CONNECTION: close
    HTTP_HOST: localhost:3000
    HTTP_USER_AGENT: Ruby
    HTTP_VERSION: HTTP/1.1
    ORIGINAL_FULLPATH: /courses/index
    ORIGINAL_SCRIPT_NAME:
    PATH_INFO: /courses/index
    QUERY_STRING:
    REMOTE_ADDR: 127.0.0.1
    REQUEST_METHOD: POST
    REQUEST_PATH: /courses/index
    REQUEST_URI: /courses/index
    ROUTES_82092800_SCRIPT_NAME:
    SCRIPT_NAME:
    SERVER_NAME: localhost
    SERVER_PORT: 3000
    SERVER_PROTOCOL: HTTP/1.1
    SERVER_SOFTWARE: puma 3.6.0 Sleepy Sunday Serenity
    action_controller.instance: #<CoursesController:0x9c32b58>
    action_dispatch.backtrace_cleaner: #<Rails::BacktraceCleaner:0x9effb9c>
    action_dispatch.cookies: #<ActionDispatch::Cookies::CookieJar:0x9bfe010>
    action_dispatch.cookies_digest:
    action_dispatch.cookies_serializer: json
    action_dispatch.encrypted_cookie_salt: encrypted cookie
    action_dispatch.encrypted_signed_cookie_salt: signed encrypted cookie
    action_dispatch.http_auth_salt: http authentication
    action_dispatch.key_generator: #<ActiveSupport::CachingKeyGenerator:0xa296aa8>
    action_dispatch.logger: #<ActiveSupport::Logger:0x9c308e4>
    action_dispatch.parameter_filter: [:password]
    action_dispatch.redirect_filter: []
    action_dispatch.remote_ip: 127.0.0.1
    action_dispatch.request.accepts: [#<Mime::Type:0x9c26b28 @synonyms=[], @symbol=nil, @string="*/*", @hash=874983820>]
    action_dispatch.request.content_type: application/x-www-form-urlencoded
    action_dispatch.request.formats: [#<Mime::Type:0x9c26b28 @synonyms=[], @symbol=nil, @string="*/*", @hash=874983820>]
    action_dispatch.request.parameters: {"a1"=>"666556", "a2"=>"53297", "a3"=>"645795", "a4"=>"600516", "a5"=>"926598", "a6"=>"84522", "a7"=>"127829", "a8"=>"551906", "a9"=>"476595", "a10"=>"2590", "a11"=>"87750", "a12"=>"648263", "a13"=>"52669", "a14"=>"811155", "a15"=>"491859", "a16"=>"36946", "a17"=>"342517", "a18"=>"510838", "a19"=>"3...
    action_dispatch.request.path_parameters: {:controller=>"courses", :action=>"index"}
    action_dispatch.request.query_parameters: {}
    action_dispatch.request.request_parameters: {"a1"=>"666556", "a2"=>"53297", "a3"=>"645795", "a4"=>"600516", "a5"=>"926598", "a6"=>"84522", "a7"=>"127829", "a8"=>"551906", "a9"=>"476595", "a10"=>"2590", "a11"=>"87750", "a12"=>"648263", "a13"=>"52669", "a14"=>"811155", "a15"=>"491859", "a16"=>"36946", "a17"=>"342517", "a18"=>"510838", "a19"=>"3...
    action_dispatch.request.unsigned_session_cookie: {}
    action_dispatch.request_id: d01b73d0-01b2-423c-8b15-4b8b4b6e2be5
    action_dispatch.routes: #<ActionDispatch::Routing::RouteSet:0x9c94600>
    action_dispatch.secret_key_base: 259c7840061e9221e709c4bbdbd55743f2a6c5ebb017553a460c4fb21c2e0372c5ebaf26cf724973d91936babaa459fe704434bd4a4b509ffe29e1d1f8e9cfe9
    action_dispatch.secret_token:
    action_dispatch.show_detailed_exceptions: true
    action_dispatch.show_exceptions: true
    action_dispatch.signed_cookie_salt: signed cookie
    puma.config: #<Puma::Configuration:0x9f7c980>
    puma.socket: #<TCPSocket:0x9f164a0>
    rack.after_reply: []
    rack.errors: #<IO:0x86d6dcc>
    rack.hijack: #<Puma::Client:0x9f1648c>
    rack.hijack?: true
    rack.input: #<StringIO:0x9f1562c>
    rack.multiprocess: false
    rack.multithread: true
    rack.request.cookie_hash: {}
    rack.request.form_hash: {"a1"=>"666556", "a2"=>"53297", "a3"=>"645795", "a4"=>"600516", "a5"=>"926598", "a6"=>"84522", "a7"=>"127829", "a8"=>"551906", "a9"=>"476595", "a10"=>"2590", "a11"=>"87750", "a12"=>"648263", "a13"=>"52669", "a14"=>"811155", "a15"=>"491859", "a16"=>"36946", "a17"=>"342517", "a18"=>"510838", "a19"=>"3...
    rack.request.form_input: #<StringIO:0x9f1562c>
    rack.request.form_vars: [FILTERED]
    rack.request.query_hash: {}
    rack.request.query_string:
    rack.run_once: false
    rack.session: #<ActionDispatch::Request::Session:0x9fa2b80>
    rack.session.options: #<ActionDispatch::Request::Session::Options:0x9fa2b44>
    rack.tempfiles: []
    rack.url_scheme: http
    rack.version: [1, 3]

Backtrace


`

**Comment by Rubysecret** [comment]
@smartinez87 we finalized all our work for issue #334 , we changed our perspective in fixing the code , adjusting the helper method (inspect_object) to check on size.

**Comment by smartinez87** [comment]
awesome, great work @Rubysecret !

**Pull request merged**
