### PR TITLE
Add the optional `data` to SNS Notifier text

### PR DESCRIPTION
**Pull request by TomK32**
I noticed that this notifier wasn't sending the extra data along like the email notifier.

### CODE REVIEW

**Comment by smartinez87** [comment]
Thanks for contributing @TomK32, looks good!

**Comment by TomK32** [comment]
Thank you for merging it Sebastian.

Uhm... a `hacktoberfest-accepted` label on this PR would be awsome, you know, t-shirts and fame :-D

**Comment by smartinez87** [comment]
there you go, well deserved!

**Comment by LeviLewis** [comment]
This is great! We were wondering why we couldn't get data to work with SNS. Is there any estimate when this might be tagged in a release?

**Pull request merged**
