### PR TITLE
Allow customizable backtrace for Slack

### PR DESCRIPTION
**Pull request by momentmaker**
Default is full backtrace. Option to specify number of lines to show.

### CODE REVIEW

**Comment by san650** [comment]
Hi @momentmaker, thanks for contributing!

Can you add a test for this option?

Take a look at https://github.com/smartinez87/exception_notification/blob/aa5f7ed5887ef63cffb473b98910efc048cfd585/test/exception_notifier/slack_notifier_test.rb to see other tests.

Please, let me know if you need help implementing it.

**Comment by momentmaker** [comment]
Hey @san650, cool. Sure thing.

**Comment by aried3r** [comment]
Any news on this? I am currently using the HEAD version of this gem in development to try it out and saw that very long stack traces get cut off in Slack, removing the formatting (the trailing ``` are cut off)

**Comment by aried3r** [comment]
stack_trace_too_long

I've forced an exception in a test app to show how the missing ``` at the end mess up the message in Slack.

**Pull request closed without merging**
