### PR TITLE
Raise required ruby version of gem to 2.1 (2.0 was dropped in 2015)

### PR DESCRIPTION
**Pull request by aried3r**
Personally I'd actually drop support for ≤2.4 or at least ≤2.3 at some point. But for now, this just mirrors what's been done in https://github.com/smartinez87/exception_notification/pull/306 from 2015.

At the same time, I updated RuboCop to the latest version that is supported by Ruby 2.1.

### CODE REVIEW

**Comment by EmilioCristalli** [comment]
@aried3r what do you mean it mirrors what was done in #306 ?

I think this will require a new major release, right?
So maybe it's worth planning it a little more, and remove support for more ruby versions and do bigger changes

**Comment by aried3r** [comment]
> @aried3r what do you mean it mirrors what was done in #306 ?

Oh, yeah, you're right! I wasn't being clear. So #306 contains this commit: https://github.com/smartinez87/exception_notification/pull/306/commits/ff27f863704d50389081f22a8cc3441fbef27409 which removes 2.0 support (at least from Travis) because it's no longer supported. I took this as an indication, that indeed, we do not know since 2015 if this gem runs with Ruby 2.0. Also, I take this as an indicator, that EOL Ruby version support used to be dropped in the past.

> I think this will require a new major release, right?

That's a tricky question. I personally think it should, but I've also seen arguments that some treat Ruby as just another dependency of a gem (see [this discussion](https://www.reddit.com/r/ruby/comments/7vtceq/when_is_it_okay_to_drop_support_for_ruby_versions/), and dependency updates do not warrant a major update, [according to SemVer](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api). That being said, I do major releases, yes.

I think people with unsupported Ruby versions would not see the updates anyway when doing `bundler outdated`.

> So maybe it's worth planning it a little more, and remove support for more ruby versions and do bigger changes

Yeah, maybe it does. I think, even with Ruby 2.3 being EOL, it makes sense to have this as the lower bound as it adds new syntax (`&.`) and frozen string literals, while 2.4 doesn't, IIRC.

**Comment by aried3r** [comment]
Hey @EmilioCristalli, how would you like to progress with this?

**Comment by EmilioCristalli** [comment]
@aried3r sorry for the delay. Will merge this

Thanks for the PR!

**Comment by aried3r** [comment]
Thank you! And no worries, we're all busy at times :)

**Pull request merged**
