### PR TITLE
Update for rails 7

### LINKED ISSUE #520: Rails 7 is out !
the  gem specs limit usage to rails <7

Do you plan to support it?

### PR DESCRIPTION
**Pull request by fwininger**
resolve #520 

Use also #522 to fix unit-tests

### CODE REVIEW

**Comment by fwininger** [comment]
@smartinez87 can you considers this PR ?

**Comment by fwininger** [comment]
@mschnitzer can you consider this PR ? and after I rebase #524

**Comment by mschnitzer** [comment]
@fwininger yes sure, I'm away this weekend, but I definitely plan to spend next week on reviewing PR's concerning Rails 7.x support.

**Review by mschnitzer — APPROVED** [review]
Test suite is passing, thanks for your contribution!

**Comment by mschnitzer** [comment]
@smartinez87 I would be fine with merging this, what's your opinion?

**Review by smartinez87 — APPROVED** [review]
looks good!

**Pull request merged**
