### PR TITLE
Added option for backtrace line with default full backtrace

### PR DESCRIPTION
**Pull request by aried3r**
This is a rebased version of #313. I simply rebased this and made no assumptions about code style, left whitespace as-is etc.

See https://github.com/smartinez87/exception_notification/pull/313#issuecomment-232612645

Fixes #313

### CODE REVIEW

**Comment by smartinez87** [comment]
hi @aried3r, I just merged another PR that causes conflict with this. can you please rebase against master so I can merge?

**Comment by aried3r** [comment]
Done, waiting for the test run now.

**Comment by smartinez87** [comment]
thanks @aried3r for contributing!

**Comment by smartinez87** [comment]
released here https://github.com/smartinez87/exception_notification/releases/tag/v4.2.1

**Pull request merged**
