### PR TITLE
Report exceptions occurring in Rake tasks and runner commands

### LINKED ISSUE #369: Merge exception_notification-rake gem
I've been using the extension gem https://github.com/nikhaldi/exception_notification-rake, which has worked great for me so far. However, it hasn't been updated in a while, and doesn't work with Rails 5.

So, I was wondering, does it make sense to have this functionality in exception_notification itself?

I know there is [documentation for background notifications](https://github.com/smartinez87/exception_notification#background-notifications), but it seems like it would be generally useful to automatically get notified of exceptions in Rake tasks too.

What do you think?

### PR DESCRIPTION
**Pull request by TylerRick**
Resolves #369

### CODE REVIEW

**Comment by TylerRick** [comment]
All right, I think this is ready for review and/or merge now.

I guess we should update the Readme, too, and mention (or change) the fact that you need to:
- Add `require 'exception_notification/rails'` below `Bundler.require` in your `config/application.rb` if you want to enable these behaviors. 
- Requiring it from an initializer is too late, because the `rake_tasks` callbacks have already been fired by that point.
- ( 'exception_notification/rails'` doesn't appear to be auto-required. Should it be?)
- You can also require `require 'exception_notification/rake'` only, if for whatever reason you only want to enable that portion.

---

I didn't add tests for the runner portion, because that would require having a Rails app in our test environment, and I see that `test/dummy`, which used to include such an app, has been removed. (But I did manually test it from my app.)

If that is desired, could you please advise how you would prefer a Rails app to be added in tests? Should we manually generate one and add it back as `test/dummy`? It seems like that would suffer from bit rot and would be one more thing we'd need to maintain. Or should we add another gem that does some of that for us? (Don't know of one off-hand.)

Or should we look into doing it how they do it in `railties/test/application/runner_test.rb` or `railties/test/commands/runner_test.rb`, where they have these handy helpers like `build_app` (to generate a fresh Rails app on the fly) and
```
output = rails("runner", "puts 'hello world", allow_failure: true)       
```
? Those appear to come from their `test/isolation/abstract_unit.rb` file, which unfortunately is not included with the `railties` gem itself, so it seems that we would have to copy and paste that into our gem if we wanted to use it. (And even then, it might require other test dependencies...)

**Comment by smartinez87** [comment]
Thank you @TylerRick for the PR, it looks great!

As you say, having `test/dummy` app was painful to maintain, so no need to go down that path again.
Can you please add the needed change in the Readme for this?

**Comment by TylerRick** [comment]
Okay, I took a stab at updating the docs!

I also added a note to the generated initializer (for people who don't read docs).

**Comment by smartinez87** [comment]
thank you @TylerRick, amazing job!

**Pull request merged**
